data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/train/r2l/train.zh"
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/train/r2l/train.en"
  sample_data:
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/train/r2l/train_sample.zh"
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/train/r2l/train_sample.en"
  valid_data:
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/test/r2l/mt03.src"
    - '/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/test/r2l/mt03.ref0'
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/test/r2l/mt03.ref1"
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/test/r2l/mt03.ref2"
    - "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/test/r2l/mt03.ref3"
  bleu_valid_reference: "/home/wangdq/njunlp_code/data/nist_zh-en_1.34m/test/r2l/mt03.ref"
  vocabularies:
    - type: "bpe"
      dict_path: "/home/public_data/nmtdata/nist_zh-en_1.34m/vocab.zh.bpe.json"
      codes: "/home/public_data/nmtdata/nist_zh-en_1.34m/codes.30k.zh"
      max_n_words: -1
    - type: "bpe"
      dict_path: "/home/public_data/nmtdata/nist_zh-en_1.34m/vocab.en.bpe.json"
      max_n_words: -1
      codes: "/home/public_data/nmtdata/nist_zh-en_1.34m/codes.30k.en"
  max_len:
    - 100
    - 100
  num_refs: 4
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 512
  d_model: 512
  d_inner_hid: 2048
  dropout: 0.1
  proj_share_weight: true
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 8000

training_configs:
  max_epochs: 50
  shuffle: true
  use_bucket: true
  batching_key: "tokens"
  batch_size: 4096
  update_cycle: 2
  valid_batch_size: 500
  bleu_valid_batch_size: 500
  bleu_valid_warmup: 1 # Start to do BLEU validation after those steps
  bleu_valid_configs:
    max_steps: 150
    beam_size: 4
    alpha: 0.0
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  num_kept_checkpoints: 10
  num_kept_best_model: 1
  disp_freq: 100 # Frequency to print information
  save_freq: 1000 # Frequency to save the model
  loss_valid_freq: 1000
  bleu_valid_freq: 1000
  early_stop_patience: 20
